pool:
    vmImage: 'ubuntu-latest'
  
variables:
    buildConfiguration: 'Release'
    sln: './orb.sln'
    tests: './Orb.Tests/Orb.Tests.csproj'
  
steps:
- task: DotNetCoreCLI@2
  displayName: 'Build OrbLang $(buildConfiguration)'
  inputs:
    command: build
    projects: $(sln)
    arguments: --configuration $(buildConfiguration)
- task: DotNetCoreCLI@1
  displayName: 'Run tests'
  inputs:
    command: test
    projects: $(tests)
# Publish Test Results
# Publish test results to Azure Pipelines
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TEST-*.xml'