pool:
  vmImage: 'ubuntu-latest'
  
variables:
    buildConfiguration: 'Release'
    sln: './src/orb.sln'
    tests: './src/Orb.Tests/Orb.Tests.csproj'
  
steps:
- task: DotNetCoreCLI@2
  displayName: 'Build OrbLang $(buildConfiguration)'
  inputs:
    command: build
    projects: $(sln)
    arguments: --configuration $(buildConfiguration)
- task: DotNetCoreCLI@1
  displayName: 'Run tests'
  inputs:
    command: test
    projects: $(tests)
    arguments: -r Orb.TestResults -l "trx;LogFileName=TEST-RESULTS.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/
# Publish Test Results
# Publish test results to Azure Pipelines
- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: always()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TEST-*.xml'
# Collect Code Coverage
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'